/*
Navicat MySQL Data Transfer

Source Server         : students
Source Server Version : 50173
Source Host           : localhost:3306
Source Database       : shop

Target Server Type    : MYSQL
Target Server Version : 50173
File Encoding         : 65001

Date: 2017-10-10 22:21:38
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for product
-- ----------------------------
DROP TABLE IF EXISTS `product`;
CREATE TABLE `product` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `price` double DEFAULT NULL,
  `imagePath` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of product
-- ----------------------------
INSERT INTO `product` VALUES ('1', 'OPPO R11 全网通4G+64G  双卡双待手机 玫瑰金色', '2799', '1.jpg');
INSERT INTO `product` VALUES ('2', '荣耀 V9 全网通 高配版 6GB+64GB 幻夜黑 移动联通电信4G手机 双卡双待', '2999', '2.jpg');
INSERT INTO `product` VALUES ('3', '小米Max2 全网通 4GB+64GB 金色 移动联通电信4G手机 双卡双待 ', '1699', '3.jpg');
INSERT INTO `product` VALUES ('4', 'AGM X2 4G全网通 三防手机 双卡双待 黑色双面玻璃6G+64G', '3699', '4.png');
INSERT INTO `product` VALUES ('5', '小米 红米Note4X 全网通版 3GB+32GB 铂银灰 移动联', '999', '5.jpg');
INSERT INTO `product` VALUES ('17', '1', '2', '1507645218847.jpg');

-- ----------------------------
-- Table structure for productdetail
-- ----------------------------
DROP TABLE IF EXISTS `productdetail`;
CREATE TABLE `productdetail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `introduction` longtext,
  `standard` longtext,
  `productId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_ivl0vlv1dlm0uabqxjt5qbot7` (`productId`),
  CONSTRAINT `FK_ivl0vlv1dlm0uabqxjt5qbot7` FOREIGN KEY (`productId`) REFERENCES `product` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of productdetail
-- ----------------------------
INSERT INTO `productdetail` VALUES ('1', '\r\n分辨率：1920*1080(FHD)\r\n后置摄像头：1600万像素；2000万像素\r\n前置摄像头：2000万像素\r\n核      数：八核\r\n频      率：2.2GHz\r\n品牌： OPPO\r\n商品名称：OPPOR11商品编号：5188000商品毛重：500.00g商品产地：中国大陆系统：安卓（Android）运行内存：4GB前置摄像头像素：1600万及以上购买方式：其他后置摄像头像素：后置双摄像头电池容量：3000mAh-3999mAh机身内存：64GB热点：骁龙芯片，双卡双待，快速', '主体\r\n品牌\r\nOPPO\r\n型号\r\nR11\r\n入网型号\r\nR11\r\n上市年份\r\n2017年\r\n上市月份\r\n6月\r\n基本信息\r\n机身颜色\r\n玫瑰金色\r\n机身长度（mm）\r\n154.5\r\n机身宽度（mm）\r\n74.8\r\n机身厚度（mm）\r\n6.8\r\n机身重量（g）\r\n约150g\r\n输入方式\r\n触控\r\n运营商标志或内容\r\n无\r\n机身材质分类\r\n金属边框；金属后盖\r\n操作系统\r\n操作系统\r\nAndroid\r\n操作系统版本\r\n基于Android 7.1.1 开发的ColorOS 3.1\r\n主芯片\r\nCPU品牌\r\n骁龙（Snapdragon)\r\nCPU频率\r\n2.2GHz\r\nCPU核数\r\n八核\r\nCPU型号\r\n骁龙660\r\n网络支持\r\n双卡机类型\r\n双卡双待单通\r\n最大支持SIM卡数量\r\n2个\r\nSIM卡类型\r\nNano SIM\r\n4G网络\r\n4G：移动（TD-LTE)；4G：联通(FDD-LTE)；4G：电信(FDD-LTE)\r\n3G/2G网络\r\n3G：移动(TD-SCDMA)；3G：联通(WCDMA)；3G：电信(CDMA2000)；2G：移动（GSM）+联通(GSM)；2G：电信(CDMA)\r\n副SIM卡类型\r\nNano SIM；副SIM卡与存储卡二选一\r\n副SIM卡4G网络\r\n不支持主副卡同时使用电信卡\r\n副SIM卡3G/2G网络\r\n不支持主副卡同时使用电信卡\r\n4G+（CA）\r\n移动4G+；联通4G+；电信4G+\r\n网络频率（2G/3G）\r\n2G：GSM 850/900/1800/1900；2G：CDMA 800；3G：TD-SCDMA 1900/2000\r\n存储\r\nROM\r\n64GB\r\nRAM\r\n4GB\r\n存储卡\r\n支持MicroSD（TF）\r\n最大存储扩展容量\r\n128GB\r\n屏幕\r\n主屏幕尺寸（英寸）\r\n5.5英寸\r\n分辨率\r\n1920*1080(FHD)\r\n屏幕材质类型\r\nAMOLED\r\n前置摄像头\r\n前置摄像头\r\n2000万像素\r\n前摄光圈大小\r\nf/2.0\r\n美颜技术\r\n支持\r\n拍照特点\r\n美颜；滤镜\r\n后置摄像头\r\n摄像头数量\r\n2个\r\n后置摄像头\r\n1600万像素；2000万像素\r\n美颜技术\r\n支持\r\n拍照特点\r\n防抖；美颜；连拍；全景；滤镜；微信小视频\r\n电池信息\r\n电池容量（mAh）\r\n3000mAh（典型值）\r\n电池是否可拆卸\r\n否\r\n充电器\r\n5V/4A\r\n闪充\r\n支持\r\n数据接口\r\n数据传输接口\r\nWIFI；蓝牙；WiFi热点；OTG接口\r\nNFC/NFC模式\r\n不支持\r\n耳机接口类型\r\n3.5mm\r\n充电接口类型\r\nMicro USB\r\n手机特性\r\n指纹识别\r\n支持\r\n语音识别\r\n支持\r\nGPS\r\n支持\r\n电子罗盘\r\n支持\r\n霍尔感应器\r\n不支持\r\n陀螺仪\r\n支持\r\n其他\r\n距离感应；呼吸灯；光线感应\r\n辅助功能\r\n常用功能\r\n录音；便签；重力感应', '1');
INSERT INTO `productdetail` VALUES ('2', '分辨率：2560×1440（Quad HD / 2K ）\r\n后置摄像头：双1200万像素\r\n前置摄像头：800万像素\r\n核      数：八核 + 微智核i6\r\n频      率：4 x CortexA53 1.8GHz + 4 x CortexA73 2.4GHz\r\n品牌： 华为（HUAWEI）\r\n商品名称：华为荣耀V9商品编号：4645290商品毛重：490.00g商品产地：中国大陆系统：安卓（Android）购买方式：其他电池容量：4000mAh-5999mAh机身颜色：黑色热点：双卡双待，快速充电，指纹识别，Type-C，2K屏，支持NFC，其他，后置双摄像头运行内存：6GB前置摄像头像素：800万-1599万后置摄像头像素：后置双摄像头，1200万-1999万机身内存：64GB', '主体\r\n品牌\r\n华为（HUAWEI）\r\n型号\r\n荣耀 V9（DUK-AL20）\r\n入网型号\r\nDUK-AL20\r\n上市年份\r\n2017年\r\n上市月份\r\n2月\r\n基本信息\r\n机身颜色\r\n幻夜黑\r\n机身长度（mm）\r\n157mm\r\n机身宽度（mm）\r\n77.5mm\r\n机身厚度（mm）\r\n6.97mm\r\n机身重量（g）\r\n约184g(含电池)\r\n运营商标志或内容\r\n其他\r\n机身材质分类\r\n金属边框；金属后盖\r\n机身材质工艺\r\n备注：受产品配置和制造工艺影响，实际机身尺寸及重量或有差异，请以实物为准！\r\n操作系统\r\n操作系统\r\nAndroid\r\n操作系统版本\r\n华为 EMUI 5.1（兼容Android 7.0）【*由于5.1新机各地区上市节奏不同，如果买到新机的操作系统是旧版本的用户，在开机后可自行升级】\r\n主芯片\r\nCPU品牌\r\n海思（Hisilicon）\r\nCPU频率\r\n4 x CortexA53 1.8GHz + 4 x CortexA73 2.4GHz\r\nCPU核数\r\n八核 + 微智核i6\r\nCPU型号\r\n麒麟960\r\nGPU型号\r\nMali G71 MP8\r\n网络支持\r\n双卡机类型\r\n双卡双待单通\r\n最大支持SIM卡数量\r\n2个\r\nSIM卡类型\r\nNano SIM\r\n4G网络\r\n4G：移动（TD-LTE)；4G：联通(FDD-LTE)；4G：电信(FDD-LTE)；4G：联通(TD-LTE)\r\n3G/2G网络\r\n3G：移动(TD-SCDMA)；3G：联通(WCDMA)；3G：电信(CDMA2000)；2G：移动（GSM）+联通(GSM)；2G：电信(CDMA)\r\n网络频率（4G）\r\nFDD-LTE：B1/B3/B5；TDD-LTE：B38/B39/B40/B41\r\n网络频率（2G/3G）\r\n其他\r\n数据业务\r\nTD-LTE/LTE FDD/TD-SCDMA/WCDMA/CDMA EVDO/EDGE/GPRS LTE FDD：最高支持到Cat6 TD-LTE：最高支持到Cat10\r\n其他\r\n支持移动/联通/电信 4G/3G/2G *卡槽1、2可任意切换为主卡、副卡;*不能同时使用2张电信卡。\r\n存储\r\nROM\r\n64GB\r\nRAM\r\n6GB\r\n存储卡\r\n支持MicroSD（TF）\r\n最大存储扩展容量\r\n128GB\r\n可用空间\r\n约48GB（备注：可使用的内存容量小于标准值，因为手机软件占用的空间）\r\n屏幕\r\n主屏幕尺寸（英寸）\r\n5.7英寸\r\n分辨率\r\n2560×1440（Quad HD / 2K ）\r\n屏幕像素密度（ppi）\r\n515\r\n屏幕材质类型\r\nLTPS\r\n屏幕色彩\r\n1670万色\r\n前置摄像头\r\n前置摄像头\r\n800万像素\r\n前摄光圈大小\r\nf/2.0\r\n美颜技术\r\n支持\r\n拍照特点\r\n美颜；全景；其他；美肤录像；水印；有声照片\r\n后置摄像头\r\n摄像头数量\r\n2个\r\n后置摄像头\r\n双1200万像素\r\n摄像头光圈大小\r\nf/2.2\r\n闪光灯\r\n双色温双LED闪光灯\r\n照片最大分辨率\r\n最大支持3968*2976像素照片拍摄\r\n拍照特点\r\n数码变焦；自动对焦；美颜；全景；HDR；其他；夜间拍摄；水印；美肤录像\r\n电池信息\r\n电池容量（mAh）\r\n4000mAh（典型容量）/3900mAh(最小容量)\r\n电池类型\r\n锂聚合物电池\r\n电池是否可拆卸\r\n否\r\n理论待机时间（小时）\r\n待机上限时间：21天备注：上述数据为实验室数据，实际待机和通话时间，视当地的实际网络情况和使用习惯而有所不同\r\n理论通话时间（小时）\r\n理论3G通话时间：30小时备注：上述数据为实验室数据，实际待机和通话时间，视当地的实际网络情况和使用习惯而有所不同\r\n充电器\r\n9V/2A\r\n数据接口\r\n数据传输接口\r\n红外；NFC；蓝牙；WiFi热点\r\nNFC/NFC模式\r\n支持（点对点模式）；支持（读卡器模式）；支持卡模拟\r\n耳机接口类型\r\n3.5mm\r\n充电接口类型\r\nType-C\r\n数据线\r\nUSB2.0\r\n手机特性\r\n指纹识别\r\n支持\r\nGPS\r\n支持\r\n电子罗盘\r\n支持\r\n霍尔感应器\r\n支持\r\n陀螺仪\r\n支持\r\n红外遥控\r\n支持\r\n其他\r\n距离感应；其他\r\n辅助功能\r\n常用功能\r\n其他；录音；重力感应\r\n其他1\r\n情景智能\r\n其他2\r\n运动健康\r\n其他3\r\n单手操作\r\n其他4\r\n语音控制\r\n其他5\r\n皮套模式\r\n其他6\r\n指关节手势\r\n包装清单\r\n手机×1、充电器×1、USB线×1、快速指南×1、售后服务手册×1、取卡针×1、VR镜片×2', '2');
INSERT INTO `productdetail` VALUES ('3', '分辨率：1920*1080(FHD)\r\n后置摄像头：1200万像素\r\n前置摄像头：500万像素\r\n核      数：八核\r\n频      率：骁龙625八核处理器 最高主频2.0GHz\r\n品牌： 小米（MI）\r\n商品名称：小米小米Max2商品编号：5159242商品毛重：430.00g商品产地：中国大陆热点：功能机，骁龙芯片，双卡双待，快速充电，指纹识别，Type-C，VoLTE，金属机身，智能机（老龄模式），拍照神器，女性手机，儿童手机，游戏手机运行内存：4GB前置摄像头像素：500万-799万后置摄像头像素：1200万-1999万电池容量：4000mAh-5999mAh机身内存：64GB机身颜色：金色', '主体\r\n品牌\r\n小米（MI）\r\n型号\r\nMax2\r\n入网型号\r\n以官网信息为准\r\n上市年份\r\n2017年\r\n上市月份\r\n5月\r\n基本信息\r\n机身颜色\r\n香槟金\r\n机身长度（mm）\r\n174.1mm\r\n机身宽度（mm）\r\n88.7mm\r\n机身厚度（mm）\r\n7.6mm\r\n机身重量（g）\r\n约211g\r\n运营商标志或内容\r\n无\r\n机身材质分类\r\n其他\r\n操作系统\r\n操作系统\r\n其他\r\n操作系统版本\r\nmiui\r\n主芯片\r\nCPU品牌\r\n骁龙（Snapdragon)\r\nCPU频率\r\n骁龙625八核处理器 最高主频2.0GHz\r\nCPU核数\r\n八核\r\nCPU型号\r\n骁龙625（MSM8953）\r\n网络支持\r\n双卡机类型\r\n双卡双待单通\r\n最大支持SIM卡数量\r\n2个\r\nSIM卡类型\r\nNano SIM\r\n4G网络\r\n4G：移动（TD-LTE)；4G：联通(FDD-LTE)；4G：电信(FDD-LTE)；4G：联通(TD-LTE)\r\n3G/2G网络\r\n3G：移动(TD-SCDMA)；3G：联通(WCDMA)；3G：电信(CDMA2000)；2G：移动（GSM）+联通(GSM)；2G：电信(CDMA)；2G：移动联通(GSM)+电信(CDMA)\r\n副SIM卡类型\r\nMicro SIM\r\n副SIM卡4G网络\r\n不支持主副卡同时使用电信卡\r\n副SIM卡3G/2G网络\r\n不支持主副卡同时使用电信卡\r\n网络频率（2G/3G）\r\n2G：GSM 850/900/1800/1900；2G：CDMA 800；3G：TD-SCDMA 1900/2000；3G：WCDMA 850/900/1900/2100；3G：CDMA2000；2G：GSM 900/1800；2G：GSM 900/1800/1900；3G：CDMA 800MHz 1X&EVDO；3G：WCDMA：850/900/1700/1900/2100MHz\r\n存储\r\nROM\r\n64GB\r\nRAM\r\n4GB\r\n存储卡\r\n支持MicroSD（TF）\r\n最大存储扩展容量\r\n128GB\r\n可用空间\r\n*实际可用容量会由于诸多因素而减少并有所差异：由于操作系统运行占据了部分内存（RAM），实际可用空间小于标识内存容量； 由于安装操作系统和预装的程序占据了部分闪存（ROM），实际可用存储空间小于标识闪存容量。\r\n屏幕\r\n主屏幕尺寸（英寸）\r\n6.44英寸\r\n分辨率\r\n1920*1080(FHD)\r\n屏幕像素密度（ppi）\r\n342\r\n屏幕材质类型\r\n其他\r\n亮度\r\n450nit\r\n对比度\r\n1000：1\r\n前置摄像头\r\n前置摄像头\r\n500万像素\r\n前摄光圈大小\r\nf/2.0\r\n美颜技术\r\n支持\r\n拍照特点\r\n美颜\r\n后置摄像头\r\n摄像头数量\r\n1个\r\n后置摄像头\r\n1200万像素\r\n摄像头光圈大小\r\nf/2.2\r\n闪光灯\r\n双色温灯\r\n美颜技术\r\n支持\r\n拍照特点\r\n美颜；连拍；全景；滤镜；HDR；PDAF\r\n电池信息\r\n电池容量（mAh）\r\n5300mAh（typ）/5200mAh（min）\r\n电池是否可拆卸\r\n否\r\n充电器\r\n9V/2A\r\n快速充电\r\n支持快充3.0\r\n数据接口\r\n数据传输接口\r\n红外；WIFI；蓝牙\r\nNFC/NFC模式\r\n不支持\r\n耳机接口类型\r\n3.5mm\r\n充电接口类型\r\nType-C\r\n手机特性\r\n指纹识别\r\n支持\r\nGPS\r\n支持\r\n电子罗盘\r\n支持\r\n霍尔感应器\r\n支持\r\n陀螺仪\r\n支持\r\n红外遥控\r\n支持\r\n其他\r\n距离感应；光线感应\r\n辅助功能\r\n常用功能\r\n录音；便签；超大字体\r\n包装清单\r\n手机主机*1、电源适配器*1、USB Type-C数据线*1、三包凭证/入门指南*1、插针*1', '3');
INSERT INTO `productdetail` VALUES ('4', '分辨率：2560×1440（Quad HD / 2K ）\r\n后置摄像头：1200万像素\r\n前置摄像头：1600万像素\r\n核      数：四核\r\n频      率：2x2.15GHz + 2x1.6GHz\r\n品牌： HTC\r\n商品名称：HTCU Ultra商品编号：5394030商品毛重：440.00g商品产地：中国大陆系统：安卓（Android）购买方式：其他电池容量：3000mAh-3999mAh机身颜色：银色热点：骁龙芯片，双卡双待，快速充电，指纹识别，Type-C，VoLTE，2K屏，拍照神器，支持NFC运行内存：4GB前置摄像头像素：1600万及以上后置摄像头像素：1200万-1999万机身内存：64GB', '主体\r\n品牌\r\nHTC\r\n型号\r\nHTC U-1w\r\n入网型号\r\nHTC U-1w\r\n上市年份\r\n2017年\r\n上市月份\r\n2月\r\n基本信息\r\n机身颜色\r\n远望（蓝）\r\n机身长度（mm）\r\n162.41mm\r\n机身宽度（mm）\r\n79.79mm\r\n机身厚度（mm）\r\n7.99mm\r\n机身重量（g）\r\n约170g\r\n输入方式\r\n触控\r\n运营商标志或内容\r\n其他\r\n机身材质分类\r\n玻璃后盖\r\n操作系统\r\n操作系统\r\nAndroid\r\n操作系统版本\r\nAndroid 7.0\r\n主芯片\r\nCPU品牌\r\n以官网信息为准\r\nCPU频率\r\n2x2.15GHz + 2x1.6GHz\r\nCPU核数\r\n四核\r\nCPU型号\r\n高通骁龙821\r\n网络支持\r\n双卡机类型\r\n双卡双待单通\r\n最大支持SIM卡数量\r\n2个\r\nSIM卡类型\r\nNano SIM\r\n4G网络\r\n4G：移动（TD-LTE)；4G：联通(FDD-LTE)；4G：电信(FDD-LTE)\r\n3G/2G网络\r\n3G：移动(TD-SCDMA)；3G：联通(WCDMA)；3G：电信(CDMA2000)；2G：移动（GSM）+联通(GSM)\r\n网络频率（2G/3G）\r\n2G：GSM 850/900/1800/1900；3G：TD-SCDMA 1900/2000；3G：WCDMA 850/900/1900/2100；3G：CDMA2000\r\n存储\r\nROM\r\n64GB\r\nRAM\r\n4GB\r\n存储卡\r\n支持MicroSD（TF）\r\n最大存储扩展容量\r\n2TB\r\n屏幕\r\n主屏幕尺寸（英寸）\r\n5.7英寸\r\n分辨率\r\n2560×1440（Quad HD / 2K ）\r\n屏幕像素密度（ppi）\r\n513\r\n屏幕材质类型\r\nSuper LCD\r\n前置摄像头\r\n前置摄像头\r\n1600万像素\r\n前摄光圈大小\r\nf/2.0\r\n拍照特点\r\nHDR\r\n后置摄像头\r\n摄像头数量\r\n1个\r\n后置摄像头\r\n1200万像素\r\n摄像头光圈大小\r\nf/1.8\r\n拍照特点\r\n自动对焦；HDR\r\n电池信息\r\n电池容量（mAh）\r\n3000 mAh\r\n电池是否可拆卸\r\n否\r\n充电器\r\n5V/2.5A\r\n快速充电\r\n支持\r\n娱乐功能\r\n视频录制格式\r\n.3gp,.mp4, .mkv\r\n数据接口\r\n数据传输接口\r\nNFC；HDMI接口；WiFi热点\r\nNFC/NFC模式\r\n支持（点对点模式）；支持（读卡器模式）；支持（卡模式）\r\n耳机接口类型\r\nType-C\r\n充电接口类型\r\nType-C\r\n手机特性\r\n指纹识别\r\n支持\r\nGPS\r\n支持\r\n电子罗盘\r\n支持\r\n陀螺仪\r\n支持\r\n其他\r\n距离感应；光线感应\r\n辅助功能\r\n常用功能\r\n收音机；录音；便签；超大字体；SOS功能；重力感应\r\n包装清单\r\nHTC USonic 智能声纳耳机× 1、电源适配器× 1、USB数据线× 1、快速入门指南× 1、安全与法规注意事项 × 1、手机真伪鉴别提示卡× 1、售后服务手册× 1、标准配件清单× 1、取卡针× 1、金爵卡× 1、透明保护壳× 1', '5');
INSERT INTO `productdetail` VALUES ('5', '分辨率：1280×720（HD）\r\n后置摄像头：1300万像素\r\n前置摄像头：1600万像素\r\n核      数：八核\r\n频      率：以官网信息为准\r\n品牌： 小米（MI）\r\n商品名称：小米红米Note5A商品编号：4787565商品毛重：300.00g商品产地：中国大陆系统：安卓（Android）运行内存：3GB前置摄像头像素：1600万及以上热点：骁龙芯片，双卡双待，指纹识别，智能机（老龄模式），拍照神器，女性手机，儿童手机，游戏手机后置摄像头像素：1200万-1999万电池容量：3000mAh-3999mAh机身内存：32GB机身颜色：金色', '主体\r\n品牌\r\n小米（MI）\r\n型号\r\n红米Note 5A\r\n入网型号\r\n以官网信息为准\r\n上市年份\r\n2017年\r\n上市月份\r\n8月\r\n基本信息\r\n机身颜色\r\n香槟金\r\n机身长度（mm）\r\n153mm\r\n机身宽度（mm）\r\n76.2mm\r\n机身厚度（mm）\r\n7.7mm\r\n机身重量（g）\r\n约153g\r\n运营商标志或内容\r\n无\r\n机身材质分类\r\n其他\r\n操作系统\r\n操作系统\r\nAndroid\r\n操作系统版本\r\nMIUI8\r\n主芯片\r\nCPU品牌\r\n骁龙（Snapdragon)\r\nCPU频率\r\n以官网信息为准\r\nCPU核数\r\n八核\r\nCPU型号\r\n骁龙435（MSM8940）\r\n网络支持\r\n双卡机类型\r\n双卡双待单通\r\n最大支持SIM卡数量\r\n2个\r\nSIM卡类型\r\nNano SIM\r\n4G网络\r\n4G：移动（TD-LTE)；4G：联通(FDD-LTE)；4G：电信(FDD-LTE)；4G：联通(TD-LTE)\r\n3G/2G网络\r\n3G：移动(TD-SCDMA)；3G：联通(WCDMA)；3G：电信(CDMA2000)；2G：移动（GSM）+联通(GSM)；2G：电信(CDMA)；2G：移动联通(GSM)+电信(CDMA)\r\n副SIM卡类型\r\nNano SIM\r\n副SIM卡4G网络\r\n不支持主副卡同时使用电信卡\r\n副SIM卡3G/2G网络\r\n不支持主副卡同时使用电信卡\r\n网络频率（2G/3G）\r\n2G：GSM 850/900/1800/1900；2G：CDMA 800；3G：TD-SCDMA 1900/2000；3G：WCDMA 850/900/1900/2100；3G：CDMA2000；2G：GSM 900/1800；2G：GSM 900/1800/1900；3G：CDMA 800MHz 1X&EVDO；3G：WCDMA：850/900/1700/1900/2100MHz\r\n存储\r\nROM\r\n32GB\r\nRAM\r\n3GB\r\n存储卡\r\n支持MicroSD（TF）\r\n最大存储扩展容量\r\n128GB\r\n可用空间\r\n*实际可用容量会由于诸多因素而减少并有所差异：由于操作系统运行占据了部分内存（RAM），实际可用空间小于标识内存容量； 由于安装操作系统和预装的程序占据了部分闪存（ROM），实际可用存储空间小于标识闪存容量。\r\n屏幕\r\n主屏幕尺寸（英寸）\r\n5.5英寸\r\n分辨率\r\n1280×720（HD）\r\n屏幕材质类型\r\n其他\r\n前置摄像头\r\n前置摄像头\r\n1600万像素\r\n前摄光圈大小\r\nf/2.0\r\n美颜技术\r\n支持\r\n拍照特点\r\n美颜\r\n后置摄像头\r\n摄像头数量\r\n1个\r\n后置摄像头\r\n1300万像素\r\n摄像头光圈大小\r\nf/2.2\r\n拍照特点\r\n连拍；全景；HDR；PDAF\r\n电池信息\r\n电池容量（mAh）\r\n3080mAh（typ）/3000mAh（min）\r\n电池是否可拆卸\r\n否\r\n充电器\r\n5V/2A\r\n数据接口\r\n数据传输接口\r\n红外；蓝牙\r\nNFC/NFC模式\r\n不支持\r\n耳机接口类型\r\n3.5mm\r\n充电接口类型\r\nMicro USB\r\n手机特性\r\n指纹识别\r\n支持\r\nGPS\r\n支持\r\n电子罗盘\r\n支持\r\n陀螺仪\r\n支持\r\n红外遥控\r\n支持\r\n其他\r\n距离感应；光线感应\r\n辅助功能\r\n常用功能\r\n录音；便签；超大字体\r\n包装清单\r\n手机主机*1、电源适配器*1、数据线*1、三包凭证/入门指南*1、插针*1', '4');
INSERT INTO `productdetail` VALUES ('21', '3', '4', '17');
